---
- name: ensure the k8s signing key is available
  apt_key:
    id: 3746C208A7317B0F
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: ensure the k8s repo is available
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main
    state: present

- name: install ceph
  apt: name={{ item }} state=installed
  with_items:
  - ceph-common
  - ceph-fs-common

- name: ensure kubernetes packages are installed
  apt: name={{ item }} state=installed
  with_items:
    - docker-engine
    - kubernetes-cni
    - kubelet={{ k8s_deb_version }}
    - kubeadm={{ k8s_deb_version }}

- name: configure docker daemon
  copy:
    dest: /etc/docker/daemon.json
    content: |
      { "insecure-registries": ["registry.default.svc.cluster.local"] }
  notify: restart docker

- meta: flush_handlers

- name: ensure the kubelet cloud env vars are present
  template:
    src: cloud-config.sh
    dest: /etc/kubernetes/cloud-config.sh

- name: ensure the kubelet cloud config is present
  template:
    src: cloud-config.ini
    dest: /etc/kubernetes/cloud-config
  notify: restart kubelet

- name: ensure the kubelet cloud dropin is present
  template:
    src: 00-cloud.conf
    dest: /etc/systemd/system/kubelet.service.d/00-cloud.conf
  notify:
  - reload systemd units
  - restart kubelet

- meta: flush_handlers

- name: make sure kubelet is enabled and running
  service:
    name: kubelet
    state: started
    enabled: yes

- name: add kube-dns to resolv.conf
  lineinfile:
    state: present
    line: nameserver 10.96.0.10
    path: /etc/resolvconf/resolv.conf.d/head
  notify: regenerate resolv.conf
