apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kakera-kazamatsuri
  annotations:
    kubernetes.io/tls-acme: "true"
  labels:
    app: kakera
spec:
  tls:
  - secretName: kakera-kazamatsuri-tls
    hosts:
    - kazamatsuri.org
    - test.kazamatsuri.org
  rules:
  - host: kazamatsuri.org
    http:
      paths:
      - path: /
        backend:
          serviceName: kakera
          servicePort: 80
  - host: test.kazamatsuri.org
    http:
      paths:
      - path: /
        backend:
          serviceName: kakera
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kakera-rokkenjima
  annotations:
    kubernetes.io/tls-acme: "true"
  labels:
    app: kakera
spec:
  tls:
  - secretName: kakera-rokkenjima-tls
    hosts:
    - rokkenjima.org
  rules:
  - host: rokkenjima.org
    http:
      paths:
      - path: /
        backend:
          serviceName: kakera
          servicePort: 80
